# Config file for turning a depthimage into an array

# ~~ Filter Config ~~
numpoints: 100
scanlines:   3
scan_rows: [ 310 , 260 , 210 ]
imagewdth: 640
imagehght: 360

# ~~ Node Config ~~
publ_rate: 30
imagtopic: /camera/depth/image_rect_raw
drivtopic: HARE_high_level_command
